/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import type { GetStaticPropsContext } from "next";
import Head from "next/head";
import { Container } from "~/components/layout/Container";

export default function Home() {
  return (
    <>
      <Head>
        <title>Comming Soon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <p>Hello World</p>
      </Container>
    </>
  );
}

export const getStaticProps = async (ctx: GetStaticPropsContext) => ({
  props: {
    messages: (await import(`../translations/${ctx.locale}.json`)).default,
  },
});
